providers:
  openai: {model_default: gpt-4.1-mini, api_key_env: OPENAI_API_KEY}
  anthropic: {model_default: claude-sonnet-4, api_key_env: ANTHROPIC_API_KEY}
  google: {model_default: gemini-2.5-flash, api_key_env: GOOGLE_API_KEY}
  perplexity: {model_default: sonar-reasoning-pro, api_key_env: PERPLEXITY_API_KEY}
  cohere: {model_default: command-r-plus, api_key_env: COHERE_API_KEY}
  xai: {model_default: grok-3, api_key_env: XAI_API_KEY}
judge:
  # model used to judge/fuser if available (falls back to heuristic if absent)
  provider: openai
  model: gpt-4.1-mini
