defaults:
  max_concurrency: 4
  retry: {tries: 2, backoff_s: 2}

budget_bands:
  low:   {in_price_max: 1.0, out_price_max: 4.0}
  mid:   {in_price_max: 3.0, out_price_max: 12.0}
  high:  {in_price_max: 15.0, out_price_max: 75.0}

routes:
  research.summary:
    low:  [{provider: google, model: gemini-2.5-flash}]
    mid:  [{provider: perplexity, model: sonar-reasoning-pro}]
    high: [{provider: anthropic, model: claude-sonnet-4}]
  code.generation:
    low:  [{provider: mistral, model: mistral-medium-3}]
    mid:  [{provider: openai, model: gpt-4.1}]
    high: [{provider: openai, model: gpt-5},{provider: anthropic, model: claude-opus-4.1}]
  reasoning.deep:
    mid:  [{provider: anthropic, model: claude-sonnet-4}]
    high: [{provider: anthropic, model: claude-opus-4.1},{provider: openai, model: gpt-5}]
  content.longform:
    low:  [{provider: openai, model: gpt-4.1-mini}]
    mid:  [{provider: anthropic, model: claude-sonnet-4}]
    high: [{provider: openai, model: gpt-5}]
